// prisma/seed-templates.ts

type SeedTemplate = {
  name: string;
  nameKo: string;
  description: string;
  descriptionKo: string;
  icon: string;
  category: string;
  tags: string[];
  blocks: object[];
};

// Helper to create heading block
const h2 = (text: string) => ({
  type: "heading",
  attrs: { level: 2 },
  content: [{ type: "text", text }],
});

const h3 = (text: string) => ({
  type: "heading",
  attrs: { level: 3 },
  content: [{ type: "text", text }],
});

const p = (text = "") =>
  text
    ? { type: "paragraph", content: [{ type: "text", text }] }
    : { type: "paragraph" };

const bullet = (...items: string[]) => ({
  type: "bulletList",
  content: items.map((t) => ({
    type: "listItem",
    content: [t ? { type: "paragraph", content: [{ type: "text", text: t }] } : { type: "paragraph" }],
  })),
});

const tasks = (...items: string[]) => ({
  type: "taskList",
  content: items.map((t) => ({
    type: "taskItem",
    attrs: { checked: false },
    content: [t ? { type: "paragraph", content: [{ type: "text", text: t }] } : { type: "paragraph" }],
  })),
});

const numbered = (...items: string[]) => ({
  type: "orderedList",
  content: items.map((t) => ({
    type: "listItem",
    content: [{ type: "paragraph", content: [{ type: "text", text: t }] }],
  })),
});

const quote = (text: string) => ({
  type: "blockquote",
  content: [{ type: "paragraph", content: [{ type: "text", text }] }],
});

const hr = () => ({ type: "horizontalRule" });

const callout = (text: string, icon = "💡") => ({
  type: "callout",
  attrs: { icon, color: "default" },
  content: [{ type: "paragraph", content: [{ type: "text", text }] }],
});

export const SEED_TEMPLATES: SeedTemplate[] = [
  // ──────────────── DOCUMENTS (10) ────────────────
  {
    name: "Meeting Notes",
    nameKo: "회의록",
    description: "Agenda, discussion points, and action items",
    descriptionKo: "안건, 토론 사항, 액션 아이템",
    icon: "📝",
    category: "documents",
    tags: ["meeting", "notes", "agenda", "회의"],
    blocks: [h2("Agenda / 안건"), bullet(""), h2("Discussion / 토론"), bullet(""), h2("Action Items / 액션 아이템"), tasks("", "")],
  },
  {
    name: "Design Document",
    nameKo: "설계 문서",
    description: "Technical design with context, goals, and solution",
    descriptionKo: "기술 설계 문서 - 맥락, 목표, 제안 솔루션",
    icon: "📐",
    category: "documents",
    tags: ["design", "technical", "rfc", "설계"],
    blocks: [h2("Context / 맥락"), p(), h2("Goals / 목표"), bullet(""), h2("Proposed Solution / 제안 솔루션"), p(), h2("Alternatives / 대안"), p(), h2("Open Questions / 미해결 질문"), tasks("")],
  },
  {
    name: "Product Requirements (PRD)",
    nameKo: "제품 요구사항 (PRD)",
    description: "Product requirements document template",
    descriptionKo: "제품 요구사항 문서 템플릿",
    icon: "📋",
    category: "documents",
    tags: ["prd", "product", "requirements", "요구사항"],
    blocks: [h2("Overview / 개요"), p(), h2("Problem Statement / 문제 정의"), p(), h2("Goals / 목표"), bullet(""), h2("User Stories / 사용자 스토리"), numbered("As a [user], I want [feature] so that [benefit]"), h2("Requirements / 요구사항"), h3("Must Have"), tasks(""), h3("Nice to Have"), tasks(""), h2("Success Metrics / 성공 지표"), bullet(""), h2("Timeline / 일정"), p()],
  },
  {
    name: "Technical Spec",
    nameKo: "기술 스펙",
    description: "API and system technical specification",
    descriptionKo: "API 및 시스템 기술 명세",
    icon: "🔧",
    category: "documents",
    tags: ["spec", "api", "technical", "기술"],
    blocks: [h2("System Overview / 시스템 개요"), p(), h2("Architecture / 아키텍처"), p(), h2("API Endpoints"), bullet("GET /api/...", "POST /api/..."), h2("Data Models / 데이터 모델"), p(), h2("Error Handling / 에러 처리"), bullet(""), h2("Security Considerations / 보안"), bullet("")],
  },
  {
    name: "Decision Record (ADR)",
    nameKo: "의사결정 기록 (ADR)",
    description: "Architecture decision record",
    descriptionKo: "아키텍처 의사결정 기록",
    icon: "⚖️",
    category: "documents",
    tags: ["adr", "decision", "architecture", "의사결정"],
    blocks: [h2("Status / 상태"), p("Proposed"), h2("Context / 맥락"), p(), h2("Decision / 결정"), p(), h2("Consequences / 결과"), bullet("Positive:", "Negative:"), h2("Alternatives Considered / 대안"), bullet("")],
  },
  {
    name: "Runbook",
    nameKo: "런북",
    description: "Operational runbook for incident response",
    descriptionKo: "장애 대응 운영 런북",
    icon: "🚨",
    category: "documents",
    tags: ["runbook", "ops", "incident", "런북"],
    blocks: [callout("Follow these steps in order during an incident.", "🚨"), h2("Symptoms / 증상"), bullet(""), h2("Diagnosis Steps / 진단"), numbered("Check service health", "Review logs", "Check dependencies"), h2("Resolution / 해결"), numbered("Step 1", "Step 2"), h2("Post-Incident / 사후 조치"), tasks("Update status page", "Write postmortem")],
  },
  {
    name: "Release Notes",
    nameKo: "릴리스 노트",
    description: "Changelog and release notes template",
    descriptionKo: "변경 로그 및 릴리스 노트",
    icon: "🚀",
    category: "documents",
    tags: ["release", "changelog", "릴리스"],
    blocks: [h2("Version X.Y.Z"), p("Release date: YYYY-MM-DD"), h2("New Features / 새 기능"), bullet(""), h2("Improvements / 개선"), bullet(""), h2("Bug Fixes / 버그 수정"), bullet(""), h2("Breaking Changes / 호환성"), callout("None in this release", "⚠️")],
  },
  {
    name: "Research Notes",
    nameKo: "리서치 노트",
    description: "User research and findings documentation",
    descriptionKo: "사용자 리서치 및 분석 문서",
    icon: "🔍",
    category: "documents",
    tags: ["research", "ux", "리서치"],
    blocks: [h2("Research Question / 연구 질문"), p(), h2("Methodology / 방법론"), p(), h2("Participants / 참여자"), bullet(""), h2("Key Findings / 주요 발견"), numbered(""), h2("Recommendations / 권장사항"), tasks("")],
  },
  {
    name: "Standard Operating Procedure",
    nameKo: "표준 운영 절차 (SOP)",
    description: "Step-by-step process documentation",
    descriptionKo: "단계별 프로세스 문서",
    icon: "📖",
    category: "documents",
    tags: ["sop", "process", "절차"],
    blocks: [h2("Purpose / 목적"), p(), h2("Scope / 범위"), p(), h2("Prerequisites / 사전 조건"), tasks(""), h2("Procedure / 절차"), numbered("Step 1", "Step 2", "Step 3"), h2("Troubleshooting / 문제 해결"), bullet("")],
  },
  {
    name: "Postmortem",
    nameKo: "포스트모템",
    description: "Incident postmortem with timeline and actions",
    descriptionKo: "장애 포스트모템 - 타임라인 및 조치",
    icon: "🔥",
    category: "documents",
    tags: ["postmortem", "incident", "포스트모템"],
    blocks: [h2("Summary / 요약"), p(), h2("Impact / 영향"), bullet("Duration:", "Users affected:", "Revenue impact:"), h2("Timeline / 타임라인"), bullet("HH:MM - Event 1", "HH:MM - Event 2"), h2("Root Cause / 근본 원인"), p(), h2("Action Items / 조치 항목"), tasks("", ""), h2("Lessons Learned / 교훈"), bullet("")],
  },

  // ──────────────── PERSONAL (10) ────────────────
  {
    name: "Todo List",
    nameKo: "할 일 목록",
    description: "Simple task tracker with sections",
    descriptionKo: "섹션별 간단한 작업 추적",
    icon: "☑️",
    category: "personal",
    tags: ["todo", "tasks", "할일"],
    blocks: [h2("Today / 오늘"), tasks("", "", ""), h2("This Week / 이번 주"), tasks(""), h2("Later / 나중에"), tasks("")],
  },
  {
    name: "Weekly Plan",
    nameKo: "주간 계획",
    description: "Weekly goals and daily breakdown",
    descriptionKo: "주간 목표 및 일별 계획",
    icon: "📅",
    category: "personal",
    tags: ["weekly", "plan", "주간"],
    blocks: [h2("Goals / 목표"), tasks(""), h2("Monday / 월요일"), p(), h2("Tuesday / 화요일"), p(), h2("Wednesday / 수요일"), p(), h2("Thursday / 목요일"), p(), h2("Friday / 금요일"), p()],
  },
  {
    name: "Daily Journal",
    nameKo: "일일 저널",
    description: "Morning check-in and evening reflection",
    descriptionKo: "아침 체크인과 저녁 회고",
    icon: "📓",
    category: "personal",
    tags: ["journal", "daily", "저널"],
    blocks: [h2("Gratitude / 감사"), bullet("", "", ""), h2("Today's Focus / 오늘의 집중"), tasks(""), h2("Reflection / 회고"), p()],
  },
  {
    name: "Reading Notes",
    nameKo: "독서 노트",
    description: "Book notes with key ideas and quotes",
    descriptionKo: "핵심 아이디어와 인용구 독서 노트",
    icon: "📚",
    category: "personal",
    tags: ["reading", "book", "독서"],
    blocks: [h2("Summary / 요약"), p(), h2("Key Ideas / 핵심 아이디어"), bullet(""), h2("Favorite Quotes / 인용구"), quote(""), h2("Action Items / 실천사항"), tasks("")],
  },
  {
    name: "Habit Tracker",
    nameKo: "습관 추적기",
    description: "Daily habit tracking checklist",
    descriptionKo: "일별 습관 체크리스트",
    icon: "🎯",
    category: "personal",
    tags: ["habit", "tracker", "습관"],
    blocks: [h2("Daily Habits / 일일 습관"), tasks("Exercise 30min / 운동 30분", "Read 20 pages / 독서 20페이지", "Meditate 10min / 명상 10분", "Drink 2L water / 물 2L", "Sleep by 11pm / 11시 취침"), hr(), h2("Weekly Review / 주간 리뷰"), p()],
  },
  {
    name: "Goal Setting",
    nameKo: "목표 설정",
    description: "Quarterly goals with OKR framework",
    descriptionKo: "OKR 프레임워크 분기 목표",
    icon: "🏆",
    category: "personal",
    tags: ["goals", "okr", "목표"],
    blocks: [h2("Vision / 비전"), p(), h2("Objective 1 / 목표 1"), p(), h3("Key Results / 핵심 결과"), tasks("KR1:", "KR2:", "KR3:"), h2("Objective 2 / 목표 2"), p(), h3("Key Results / 핵심 결과"), tasks("KR1:", "KR2:", "KR3:")],
  },
  {
    name: "Travel Planner",
    nameKo: "여행 계획",
    description: "Trip planning with itinerary and packing",
    descriptionKo: "일정 및 짐 목록 여행 계획",
    icon: "✈️",
    category: "personal",
    tags: ["travel", "trip", "여행"],
    blocks: [h2("Destination / 목적지"), p(), h2("Dates / 일정"), p(), h2("Accommodation / 숙소"), bullet(""), h2("Itinerary / 여행 일정"), h3("Day 1"), bullet(""), h3("Day 2"), bullet(""), h2("Packing List / 짐 목록"), tasks("Passport / 여권", "Charger / 충전기", "Clothes / 옷")],
  },
  {
    name: "Recipe",
    nameKo: "레시피",
    description: "Cooking recipe with ingredients and steps",
    descriptionKo: "재료 및 조리법 레시피",
    icon: "🍳",
    category: "personal",
    tags: ["recipe", "cooking", "레시피"],
    blocks: [h2("Ingredients / 재료"), bullet(""), h2("Instructions / 조리법"), numbered("Step 1", "Step 2", "Step 3"), h2("Notes / 메모"), p()],
  },
  {
    name: "Budget Planner",
    nameKo: "예산 계획",
    description: "Monthly budget tracking",
    descriptionKo: "월별 예산 관리",
    icon: "💰",
    category: "personal",
    tags: ["budget", "finance", "예산"],
    blocks: [h2("Income / 수입"), bullet("Salary / 급여:", "Other / 기타:"), h2("Fixed Expenses / 고정 지출"), bullet("Rent / 월세:", "Insurance / 보험:", "Subscriptions / 구독:"), h2("Variable Expenses / 변동 지출"), bullet("Food / 식비:", "Transport / 교통:", "Entertainment / 여가:"), h2("Savings Goal / 저축 목표"), p()],
  },
  {
    name: "Morning Routine",
    nameKo: "아침 루틴",
    description: "Daily morning routine checklist",
    descriptionKo: "매일 아침 루틴 체크리스트",
    icon: "🌅",
    category: "personal",
    tags: ["routine", "morning", "루틴"],
    blocks: [h2("Morning Routine / 아침 루틴"), tasks("Wake up at 6:00 / 6시 기상", "Stretch / 스트레칭", "Meditate 10min / 명상 10분", "Journal / 저널 쓰기", "Healthy breakfast / 건강한 아침"), callout("Consistency is key! / 꾸준함이 핵심!", "💪")],
  },

  // ──────────────── TEAM (10) ────────────────
  {
    name: "1:1 Meeting",
    nameKo: "1:1 미팅",
    description: "Recurring meeting notes with action items",
    descriptionKo: "정기 미팅 노트 및 액션 아이템",
    icon: "🤝",
    category: "team",
    tags: ["meeting", "1on1", "미팅"],
    blocks: [h2("Updates / 업데이트"), bullet(""), h2("Discussion / 토론"), bullet(""), h2("Action Items / 액션 아이템"), tasks("", "")],
  },
  {
    name: "Sprint Retrospective",
    nameKo: "스프린트 회고",
    description: "What went well, what to improve",
    descriptionKo: "잘한 점, 개선할 점",
    icon: "🔄",
    category: "team",
    tags: ["sprint", "retro", "회고"],
    blocks: [h2("What went well / 잘한 점"), bullet(""), h2("What could improve / 개선할 점"), bullet(""), h2("Action Items / 액션 아이템"), tasks("")],
  },
  {
    name: "Sprint Planning",
    nameKo: "스프린트 계획",
    description: "Sprint goals and task breakdown",
    descriptionKo: "스프린트 목표 및 작업 분배",
    icon: "🏃",
    category: "team",
    tags: ["sprint", "planning", "계획"],
    blocks: [h2("Sprint Goal / 스프린트 목표"), p(), h2("Capacity / 가용 인력"), bullet(""), h2("Backlog Items / 백로그"), tasks("", "", "", ""), h2("Risks / 리스크"), bullet("")],
  },
  {
    name: "Team Standup",
    nameKo: "팀 스탠드업",
    description: "Daily standup notes",
    descriptionKo: "일일 스탠드업 미팅 노트",
    icon: "🧑‍💻",
    category: "team",
    tags: ["standup", "daily", "스탠드업"],
    blocks: [h2("Yesterday / 어제"), bullet(""), h2("Today / 오늘"), bullet(""), h2("Blockers / 차단 요소"), bullet("")],
  },
  {
    name: "Team Wiki",
    nameKo: "팀 위키",
    description: "Team knowledge base home page",
    descriptionKo: "팀 지식 베이스 홈페이지",
    icon: "📖",
    category: "team",
    tags: ["wiki", "knowledge", "위키"],
    blocks: [h2("Welcome / 환영합니다"), p("This is the team wiki. Add important links and docs below."), h2("Quick Links / 빠른 링크"), bullet("Getting Started", "Code Standards", "Design System"), h2("Team Members / 팀원"), bullet(""), h2("Processes / 프로세스"), bullet("")],
  },
  {
    name: "Onboarding Checklist",
    nameKo: "온보딩 체크리스트",
    description: "New team member onboarding",
    descriptionKo: "신규 팀원 온보딩",
    icon: "👋",
    category: "team",
    tags: ["onboarding", "checklist", "온보딩"],
    blocks: [h2("Day 1"), tasks("Set up accounts", "Meet the team", "Read team wiki"), h2("Week 1"), tasks("Complete dev environment setup", "Read codebase overview", "First PR"), h2("Month 1"), tasks("Complete first feature", "Participate in code review", "Present in team meeting")],
  },
  {
    name: "Team OKRs",
    nameKo: "팀 OKR",
    description: "Team quarterly objectives and key results",
    descriptionKo: "팀 분기 목표 및 핵심 결과",
    icon: "🎯",
    category: "team",
    tags: ["okr", "objectives", "OKR"],
    blocks: [h2("Q1 Objectives / Q1 목표"), h3("Objective 1"), tasks("KR1:", "KR2:", "KR3:"), h3("Objective 2"), tasks("KR1:", "KR2:"), hr(), h2("Status / 진행 상황"), p("Last updated: ")],
  },
  {
    name: "Interview Scorecard",
    nameKo: "면접 평가표",
    description: "Structured interview evaluation form",
    descriptionKo: "구조화된 면접 평가 양식",
    icon: "📊",
    category: "team",
    tags: ["interview", "hiring", "면접"],
    blocks: [h2("Candidate / 후보자"), p("Name:"), p("Position:"), p("Date:"), h2("Technical Skills / 기술 역량"), bullet("Problem solving: /5", "System design: /5", "Coding: /5"), h2("Culture Fit / 문화 적합"), bullet("Communication: /5", "Teamwork: /5"), h2("Overall / 종합"), p("Strong hire / Hire / No hire"), h2("Notes / 메모"), p()],
  },
  {
    name: "Decision Matrix",
    nameKo: "의사결정 매트릭스",
    description: "Compare options with weighted criteria",
    descriptionKo: "가중치 기준으로 옵션 비교",
    icon: "🧮",
    category: "team",
    tags: ["decision", "matrix", "의사결정"],
    blocks: [h2("Decision / 결정 사항"), p(), h2("Options / 옵션"), bullet("Option A:", "Option B:", "Option C:"), h2("Criteria / 기준"), bullet("Cost (weight: 3)", "Speed (weight: 2)", "Quality (weight: 3)"), h2("Recommendation / 권장"), p()],
  },
  {
    name: "All-Hands Meeting",
    nameKo: "전체 회의",
    description: "Company all-hands meeting agenda",
    descriptionKo: "전사 회의 안건",
    icon: "🏢",
    category: "team",
    tags: ["all-hands", "company", "전체회의"],
    blocks: [h2("Company Updates / 회사 소식"), bullet(""), h2("Team Highlights / 팀 하이라이트"), bullet(""), h2("Q&A / 질의응답"), bullet(""), h2("Action Items / 액션 아이템"), tasks("")],
  },

  // ──────────────── PROJECT (10) ────────────────
  {
    name: "Project Brief",
    nameKo: "프로젝트 브리프",
    description: "Project overview with goals, scope, timeline",
    descriptionKo: "프로젝트 개요 - 목표, 범위, 일정",
    icon: "🎯",
    category: "project",
    tags: ["project", "brief", "프로젝트"],
    blocks: [h2("Overview / 개요"), p(), h2("Goals / 목표"), bullet(""), h2("Scope / 범위"), p(), h2("Timeline / 일정"), p(), h2("Team / 팀"), bullet("")],
  },
  {
    name: "Project Status Update",
    nameKo: "프로젝트 상태 업데이트",
    description: "Weekly project progress report",
    descriptionKo: "주간 프로젝트 진행 보고",
    icon: "📊",
    category: "project",
    tags: ["status", "report", "보고"],
    blocks: [callout("Status: On Track / 상태: 정상", "🟢"), h2("Progress / 진행 상황"), bullet(""), h2("Completed This Week / 이번 주 완료"), tasks(""), h2("Next Week / 다음 주 계획"), tasks(""), h2("Risks & Blockers / 리스크"), bullet("")],
  },
  {
    name: "Project Kickoff",
    nameKo: "프로젝트 킥오프",
    description: "Project kickoff meeting template",
    descriptionKo: "프로젝트 킥오프 미팅 템플릿",
    icon: "🚀",
    category: "project",
    tags: ["kickoff", "project", "킥오프"],
    blocks: [h2("Project Vision / 비전"), p(), h2("Team & Roles / 팀 & 역할"), bullet("PM:", "Design:", "Engineering:", "QA:"), h2("Milestones / 마일스톤"), numbered("Phase 1:", "Phase 2:", "Phase 3:"), h2("Communication Plan / 소통 계획"), bullet("Standup: Daily", "Review: Weekly"), h2("Questions / 질문"), bullet("")],
  },
  {
    name: "Feature Spec",
    nameKo: "기능 스펙",
    description: "Feature specification with user stories",
    descriptionKo: "사용자 스토리 기반 기능 명세",
    icon: "💡",
    category: "project",
    tags: ["feature", "spec", "기능"],
    blocks: [h2("Feature / 기능"), p(), h2("Problem / 문제"), p(), h2("User Stories / 사용자 스토리"), bullet("As a [user], I want [feature] so that [benefit]"), h2("Design / 디자인"), p(), h2("Acceptance Criteria / 인수 조건"), tasks("", ""), h2("Edge Cases / 엣지 케이스"), bullet("")],
  },
  {
    name: "Roadmap",
    nameKo: "로드맵",
    description: "Quarterly product roadmap",
    descriptionKo: "분기별 제품 로드맵",
    icon: "🗺️",
    category: "project",
    tags: ["roadmap", "planning", "로드맵"],
    blocks: [h2("Q1"), h3("Theme / 테마"), p(), tasks("Feature 1", "Feature 2"), h2("Q2"), h3("Theme / 테마"), p(), tasks("Feature 3", "Feature 4"), h2("Q3"), h3("Theme / 테마"), p(), tasks("Feature 5"), h2("Q4"), h3("Theme / 테마"), p(), tasks("Feature 6")],
  },
  {
    name: "Risk Assessment",
    nameKo: "리스크 평가",
    description: "Project risk identification and mitigation",
    descriptionKo: "프로젝트 리스크 식별 및 완화",
    icon: "⚠️",
    category: "project",
    tags: ["risk", "assessment", "리스크"],
    blocks: [h2("High Risk / 높은 리스크"), bullet("Risk: | Impact: High | Likelihood: High | Mitigation:"), h2("Medium Risk / 중간 리스크"), bullet("Risk: | Impact: Medium | Likelihood: Medium | Mitigation:"), h2("Low Risk / 낮은 리스크"), bullet(""), h2("Contingency Plans / 비상 계획"), bullet("")],
  },
  {
    name: "Launch Checklist",
    nameKo: "출시 체크리스트",
    description: "Product/feature launch readiness checklist",
    descriptionKo: "제품/기능 출시 준비 체크리스트",
    icon: "🎉",
    category: "project",
    tags: ["launch", "checklist", "출시"],
    blocks: [h2("Pre-Launch / 출시 전"), tasks("QA complete", "Docs updated", "Monitoring set up", "Rollback plan ready"), h2("Launch Day / 출시일"), tasks("Deploy to production", "Verify in production", "Update status page", "Announce to team"), h2("Post-Launch / 출시 후"), tasks("Monitor metrics", "Collect feedback", "Address critical bugs")],
  },
  {
    name: "Competitive Analysis",
    nameKo: "경쟁사 분석",
    description: "Competitor comparison and analysis",
    descriptionKo: "경쟁사 비교 및 분석",
    icon: "🏁",
    category: "project",
    tags: ["competitive", "analysis", "경쟁사"],
    blocks: [h2("Overview / 개요"), p(), h2("Competitor A"), bullet("Strengths:", "Weaknesses:", "Pricing:"), h2("Competitor B"), bullet("Strengths:", "Weaknesses:", "Pricing:"), h2("Our Advantages / 우리의 장점"), bullet(""), h2("Opportunities / 기회"), bullet("")],
  },
  {
    name: "Stakeholder Map",
    nameKo: "이해관계자 맵",
    description: "Stakeholder identification and management",
    descriptionKo: "이해관계자 식별 및 관리",
    icon: "🗂️",
    category: "project",
    tags: ["stakeholder", "management", "이해관계자"],
    blocks: [h2("Key Stakeholders / 주요 이해관계자"), bullet("Name: | Role: | Interest: | Influence:"), h2("Communication Plan / 소통 계획"), bullet("Weekly update to:", "Monthly review with:"), h2("Approvals Needed / 필요 승인"), tasks("")],
  },
  {
    name: "Lessons Learned",
    nameKo: "프로젝트 교훈",
    description: "Project retrospective and lessons learned",
    descriptionKo: "프로젝트 회고 및 교훈",
    icon: "🎓",
    category: "project",
    tags: ["lessons", "retrospective", "교훈"],
    blocks: [h2("Project Summary / 요약"), p(), h2("What Went Well / 잘한 점"), bullet(""), h2("What Didn't / 아쉬운 점"), bullet(""), h2("Key Learnings / 핵심 교훈"), numbered(""), h2("Recommendations / 권장사항"), bullet("")],
  },

  // ──────────────── ENGINEERING (10) ────────────────
  {
    name: "Bug Report",
    nameKo: "버그 리포트",
    description: "Bug tracking with steps to reproduce",
    descriptionKo: "재현 방법 포함 버그 리포트",
    icon: "🐛",
    category: "engineering",
    tags: ["bug", "report", "버그"],
    blocks: [h2("Description / 설명"), p(), h2("Steps to Reproduce / 재현 방법"), numbered("", ""), h2("Expected / 기대 동작"), p(), h2("Actual / 실제 동작"), p(), h2("Environment / 환경"), bullet("OS:", "Browser:", "Version:")],
  },
  {
    name: "Code Review Checklist",
    nameKo: "코드 리뷰 체크리스트",
    description: "Structured code review checklist",
    descriptionKo: "구조화된 코드 리뷰 체크리스트",
    icon: "✅",
    category: "engineering",
    tags: ["code review", "checklist", "리뷰"],
    blocks: [h2("PR Overview"), p("PR #:"), p("Author:"), h2("Checklist"), tasks("Code compiles without errors", "Tests pass", "No hardcoded secrets", "Error handling present", "Follows coding standards", "Documentation updated", "No unnecessary console.log"), h2("Comments / 코멘트"), bullet("")],
  },
  {
    name: "Database Migration Plan",
    nameKo: "DB 마이그레이션 계획",
    description: "Database schema migration planning",
    descriptionKo: "데이터베이스 스키마 마이그레이션 계획",
    icon: "🗄️",
    category: "engineering",
    tags: ["database", "migration", "마이그레이션"],
    blocks: [h2("Changes / 변경 사항"), bullet(""), h2("Migration Script"), p(), h2("Rollback Plan / 롤백 계획"), p(), h2("Testing / 테스트"), tasks("Test on staging", "Verify data integrity", "Performance check"), h2("Deployment Steps / 배포 절차"), numbered("Backup database", "Run migration", "Verify", "Update application")],
  },
  {
    name: "Architecture Overview",
    nameKo: "아키텍처 개요",
    description: "System architecture documentation",
    descriptionKo: "시스템 아키텍처 문서",
    icon: "🏗️",
    category: "engineering",
    tags: ["architecture", "system", "아키텍처"],
    blocks: [h2("System Diagram / 시스템 다이어그램"), p(), h2("Components / 컴포넌트"), bullet("Frontend:", "Backend:", "Database:", "Cache:"), h2("Data Flow / 데이터 흐름"), numbered(""), h2("Infrastructure / 인프라"), bullet(""), h2("Monitoring / 모니터링"), bullet("")],
  },
  {
    name: "API Documentation",
    nameKo: "API 문서",
    description: "REST API endpoint documentation",
    descriptionKo: "REST API 엔드포인트 문서",
    icon: "🔌",
    category: "engineering",
    tags: ["api", "docs", "API"],
    blocks: [h2("Base URL"), p("`https://api.example.com/v1`"), h2("Authentication / 인증"), p("Bearer token in Authorization header"), h2("Endpoints"), h3("GET /resource"), p("Description:"), p("Response:"), h3("POST /resource"), p("Description:"), p("Request body:"), p("Response:"), h2("Error Codes / 에러 코드"), bullet("400: Bad Request", "401: Unauthorized", "404: Not Found")],
  },
  {
    name: "On-Call Handoff",
    nameKo: "온콜 인수인계",
    description: "On-call rotation handoff notes",
    descriptionKo: "온콜 교대 인수인계 노트",
    icon: "📟",
    category: "engineering",
    tags: ["oncall", "handoff", "온콜"],
    blocks: [h2("Active Issues / 진행 중 이슈"), bullet(""), h2("Resolved This Rotation / 해결된 이슈"), bullet(""), h2("Known Risks / 알려진 리스크"), bullet(""), h2("Upcoming / 예정"), bullet(""), h2("Useful Commands / 유용한 명령어"), p()],
  },
  {
    name: "Performance Review",
    nameKo: "성능 분석",
    description: "App performance audit checklist",
    descriptionKo: "앱 성능 감사 체크리스트",
    icon: "⚡",
    category: "engineering",
    tags: ["performance", "audit", "성능"],
    blocks: [h2("Metrics / 지표"), bullet("LCP:", "FID:", "CLS:", "TTFB:"), h2("Issues Found / 발견된 이슈"), bullet(""), h2("Optimizations / 최적화"), tasks("Optimize images", "Code splitting", "Cache headers", "Database queries"), h2("Results / 결과"), p()],
  },
  {
    name: "Security Audit",
    nameKo: "보안 감사",
    description: "Security review checklist",
    descriptionKo: "보안 검토 체크리스트",
    icon: "🔒",
    category: "engineering",
    tags: ["security", "audit", "보안"],
    blocks: [h2("Authentication / 인증"), tasks("Rate limiting", "Password policy", "Session management", "MFA support"), h2("Authorization / 인가"), tasks("Role-based access", "Resource ownership checks"), h2("Data Protection / 데이터 보호"), tasks("Encryption at rest", "Encryption in transit", "PII handling"), h2("Findings / 발견사항"), bullet("")],
  },
  {
    name: "Dependency Update",
    nameKo: "의존성 업데이트",
    description: "Track and plan dependency updates",
    descriptionKo: "의존성 업데이트 추적 및 계획",
    icon: "📦",
    category: "engineering",
    tags: ["dependencies", "update", "의존성"],
    blocks: [h2("Critical Updates / 긴급"), tasks(""), h2("Major Updates / 메이저"), tasks(""), h2("Minor/Patch / 마이너"), tasks(""), h2("Breaking Changes / 호환성"), bullet(""), h2("Test Plan / 테스트"), tasks("Run full test suite", "Smoke test production")],
  },
  {
    name: "Deployment Checklist",
    nameKo: "배포 체크리스트",
    description: "Production deployment checklist",
    descriptionKo: "프로덕션 배포 체크리스트",
    icon: "🚢",
    category: "engineering",
    tags: ["deploy", "checklist", "배포"],
    blocks: [h2("Pre-Deploy / 배포 전"), tasks("All tests pass", "Code reviewed and approved", "Staging verified", "Database migrations ready", "Feature flags configured"), h2("Deploy / 배포"), tasks("Deploy to production", "Run smoke tests", "Monitor error rates"), h2("Post-Deploy / 배포 후"), tasks("Verify in production", "Update changelog", "Notify stakeholders")],
  },

  // ──────────────── EDUCATION (10) ────────────────
  {
    name: "Lecture Notes",
    nameKo: "강의 노트",
    description: "Class lecture notes with key concepts",
    descriptionKo: "수업 강의 노트 - 핵심 개념",
    icon: "🎒",
    category: "education",
    tags: ["lecture", "notes", "강의"],
    blocks: [h2("Topic / 주제"), p(), h2("Key Concepts / 핵심 개념"), bullet(""), h2("Examples / 예시"), p(), h2("Questions / 질문"), bullet(""), h2("Summary / 요약"), p()],
  },
  {
    name: "Study Plan",
    nameKo: "학습 계획",
    description: "Exam preparation study plan",
    descriptionKo: "시험 대비 학습 계획",
    icon: "📖",
    category: "education",
    tags: ["study", "plan", "학습"],
    blocks: [h2("Exam Date / 시험 일자"), p(), h2("Topics to Cover / 학습 범위"), tasks("", "", ""), h2("Study Schedule / 학습 일정"), h3("Week 1"), tasks(""), h3("Week 2"), tasks(""), h2("Resources / 참고 자료"), bullet("")],
  },
  {
    name: "Cornell Notes",
    nameKo: "코넬 노트",
    description: "Cornell note-taking method template",
    descriptionKo: "코넬 노트 필기법 템플릿",
    icon: "📝",
    category: "education",
    tags: ["cornell", "notes", "코넬"],
    blocks: [h2("Cue Column / 키워드"), bullet(""), h2("Notes / 노트"), p(), hr(), h2("Summary / 요약"), p()],
  },
  {
    name: "Flashcard Set",
    nameKo: "플래시카드 세트",
    description: "Study flashcards with Q&A pairs",
    descriptionKo: "Q&A 형식 학습 플래시카드",
    icon: "🃏",
    category: "education",
    tags: ["flashcard", "study", "플래시카드"],
    blocks: [h2("Card 1"), h3("Q:"), p(), h3("A:"), p(), hr(), h2("Card 2"), h3("Q:"), p(), h3("A:"), p(), hr(), h2("Card 3"), h3("Q:"), p(), h3("A:"), p()],
  },
  {
    name: "Essay Outline",
    nameKo: "에세이 개요",
    description: "Essay writing outline structure",
    descriptionKo: "에세이 작성 개요 구조",
    icon: "✍️",
    category: "education",
    tags: ["essay", "writing", "에세이"],
    blocks: [h2("Thesis / 논제"), p(), h2("Introduction / 서론"), p(), h2("Body Paragraph 1 / 본론 1"), p("Topic sentence:"), bullet("Evidence:", "Analysis:"), h2("Body Paragraph 2 / 본론 2"), p("Topic sentence:"), bullet("Evidence:", "Analysis:"), h2("Body Paragraph 3 / 본론 3"), p("Topic sentence:"), bullet("Evidence:", "Analysis:"), h2("Conclusion / 결론"), p()],
  },
  {
    name: "Lab Report",
    nameKo: "실험 보고서",
    description: "Science lab report template",
    descriptionKo: "과학 실험 보고서 템플릿",
    icon: "🔬",
    category: "education",
    tags: ["lab", "science", "실험"],
    blocks: [h2("Title / 제목"), p(), h2("Hypothesis / 가설"), p(), h2("Materials / 재료"), bullet(""), h2("Procedure / 실험 방법"), numbered("", ""), h2("Results / 결과"), p(), h2("Conclusion / 결론"), p()],
  },
  {
    name: "Book Report",
    nameKo: "독후감",
    description: "Book review and analysis",
    descriptionKo: "독서 감상 및 분석",
    icon: "📕",
    category: "education",
    tags: ["book", "report", "독후감"],
    blocks: [h2("Book Info / 도서 정보"), bullet("Title:", "Author:", "Genre:", "Pages:"), h2("Summary / 줄거리"), p(), h2("Characters / 등장인물"), bullet(""), h2("Themes / 주제"), bullet(""), h2("My Opinion / 내 생각"), p(), h2("Rating / 평점"), p("★★★★☆")],
  },
  {
    name: "Research Paper Outline",
    nameKo: "연구 논문 개요",
    description: "Academic research paper structure",
    descriptionKo: "학술 연구 논문 구조",
    icon: "🎓",
    category: "education",
    tags: ["research", "paper", "논문"],
    blocks: [h2("Abstract / 초록"), p(), h2("Introduction / 서론"), p(), h2("Literature Review / 문헌 검토"), p(), h2("Methodology / 연구 방법"), p(), h2("Results / 결과"), p(), h2("Discussion / 토론"), p(), h2("Conclusion / 결론"), p(), h2("References / 참고문헌"), bullet("")],
  },
  {
    name: "Presentation Outline",
    nameKo: "발표 개요",
    description: "Presentation slide planning",
    descriptionKo: "발표 슬라이드 계획",
    icon: "🎤",
    category: "education",
    tags: ["presentation", "slides", "발표"],
    blocks: [h2("Title Slide / 표지"), p("Topic:"), p("Presenter:"), h2("Introduction / 서론"), bullet("Hook:", "Overview:"), h2("Main Points / 핵심 내용"), h3("Point 1"), bullet(""), h3("Point 2"), bullet(""), h3("Point 3"), bullet(""), h2("Conclusion / 결론"), bullet(""), h2("Q&A")],
  },
  {
    name: "Course Syllabus",
    nameKo: "강의 계획서",
    description: "Course syllabus and schedule",
    descriptionKo: "강의 계획서 및 일정",
    icon: "📚",
    category: "education",
    tags: ["course", "syllabus", "강의계획"],
    blocks: [h2("Course Info / 강좌 정보"), bullet("Course:", "Instructor:", "Schedule:", "Office hours:"), h2("Description / 설명"), p(), h2("Objectives / 학습 목표"), numbered(""), h2("Schedule / 일정"), h3("Week 1"), p(), h3("Week 2"), p(), h2("Grading / 평가"), bullet("Assignments: 40%", "Midterm: 25%", "Final: 35%")],
  },

  // ──────────────── MARKETING (10) ────────────────
  {
    name: "Content Calendar",
    nameKo: "콘텐츠 캘린더",
    description: "Monthly content planning calendar",
    descriptionKo: "월간 콘텐츠 계획 캘린더",
    icon: "📆",
    category: "marketing",
    tags: ["content", "calendar", "콘텐츠"],
    blocks: [h2("Month / 월"), p(), h2("Week 1"), bullet("Blog:", "Social:", "Email:"), h2("Week 2"), bullet("Blog:", "Social:", "Email:"), h2("Week 3"), bullet("Blog:", "Social:", "Email:"), h2("Week 4"), bullet("Blog:", "Social:", "Email:")],
  },
  {
    name: "Blog Post Template",
    nameKo: "블로그 포스트",
    description: "Blog post writing template with SEO",
    descriptionKo: "SEO 포함 블로그 포스트 작성 템플릿",
    icon: "✏️",
    category: "marketing",
    tags: ["blog", "post", "블로그"],
    blocks: [h2("Title / 제목"), p(), h2("Meta Description / 메타 설명"), p("(150 characters max)"), h2("Keywords / 키워드"), bullet(""), h2("Introduction / 서론"), p(), h2("Main Content / 본문"), h3("Section 1"), p(), h3("Section 2"), p(), h2("Conclusion / 결론"), p(), h2("CTA / 행동 유도"), p()],
  },
  {
    name: "Social Media Plan",
    nameKo: "소셜 미디어 계획",
    description: "Social media content strategy",
    descriptionKo: "소셜 미디어 콘텐츠 전략",
    icon: "📱",
    category: "marketing",
    tags: ["social", "media", "소셜"],
    blocks: [h2("Platform Strategy / 플랫폼 전략"), h3("Instagram"), bullet("Frequency:", "Content type:", "Hashtags:"), h3("Twitter"), bullet("Frequency:", "Content type:"), h3("LinkedIn"), bullet("Frequency:", "Content type:"), h2("Monthly Themes / 월간 테마"), bullet(""), h2("Metrics / 지표"), bullet("Followers:", "Engagement:", "Clicks:")],
  },
  {
    name: "Campaign Brief",
    nameKo: "캠페인 브리프",
    description: "Marketing campaign planning brief",
    descriptionKo: "마케팅 캠페인 계획 브리프",
    icon: "📣",
    category: "marketing",
    tags: ["campaign", "brief", "캠페인"],
    blocks: [h2("Campaign Name / 캠페인명"), p(), h2("Objective / 목표"), p(), h2("Target Audience / 타겟"), bullet("Demographics:", "Interests:", "Pain points:"), h2("Key Message / 핵심 메시지"), p(), h2("Channels / 채널"), bullet(""), h2("Budget / 예산"), p(), h2("Timeline / 일정"), p(), h2("Success Metrics / 성공 지표"), bullet("")],
  },
  {
    name: "Email Newsletter",
    nameKo: "이메일 뉴스레터",
    description: "Email newsletter content template",
    descriptionKo: "이메일 뉴스레터 콘텐츠 템플릿",
    icon: "📧",
    category: "marketing",
    tags: ["email", "newsletter", "뉴스레터"],
    blocks: [h2("Subject Line / 제목"), p(), h2("Preview Text / 미리보기"), p(), h2("Header / 헤더"), p(), h2("Main Story / 주요 내용"), p(), h2("Secondary Content / 보조 내용"), bullet(""), h2("CTA / 행동 유도"), p(), h2("Footer Note / 하단 메모"), p()],
  },
  {
    name: "Product Launch Plan",
    nameKo: "제품 출시 계획",
    description: "Product launch marketing plan",
    descriptionKo: "제품 출시 마케팅 계획",
    icon: "🎪",
    category: "marketing",
    tags: ["launch", "product", "출시"],
    blocks: [h2("Product / 제품"), p(), h2("Launch Date / 출시일"), p(), h2("Pre-Launch / 출시 전"), tasks("Teaser campaign", "Press kit", "Beta access"), h2("Launch Day / 출시일"), tasks("Press release", "Social media blitz", "Email blast", "Product Hunt"), h2("Post-Launch / 출시 후"), tasks("Monitor feedback", "Iterate messaging", "Case studies")],
  },
  {
    name: "Competitor Watch",
    nameKo: "경쟁사 모니터링",
    description: "Track competitor moves and updates",
    descriptionKo: "경쟁사 동향 추적",
    icon: "👀",
    category: "marketing",
    tags: ["competitor", "watch", "경쟁사"],
    blocks: [h2("Competitor A"), bullet("Latest update:", "New features:", "Pricing changes:", "Marketing activity:"), h2("Competitor B"), bullet("Latest update:", "New features:", "Pricing changes:", "Marketing activity:"), h2("Opportunities / 기회"), bullet(""), h2("Our Response / 대응"), tasks("")],
  },
  {
    name: "Brand Guidelines",
    nameKo: "브랜드 가이드라인",
    description: "Brand identity and usage guidelines",
    descriptionKo: "브랜드 아이덴티티 및 사용 가이드",
    icon: "🎨",
    category: "marketing",
    tags: ["brand", "guidelines", "브랜드"],
    blocks: [h2("Mission / 미션"), p(), h2("Values / 가치"), bullet(""), h2("Logo Usage / 로고 사용"), p(), h2("Color Palette / 컬러 팔레트"), bullet("Primary:", "Secondary:", "Accent:"), h2("Typography / 타이포그래피"), bullet("Heading:", "Body:", "Mono:"), h2("Voice & Tone / 보이스 & 톤"), p(), h2("Do's and Don'ts / 올바른 사용"), bullet("")],
  },
  {
    name: "Event Planning",
    nameKo: "이벤트 계획",
    description: "Event organization and logistics",
    descriptionKo: "이벤트 조직 및 운영 계획",
    icon: "🎪",
    category: "marketing",
    tags: ["event", "planning", "이벤트"],
    blocks: [h2("Event Details / 이벤트 정보"), bullet("Name:", "Date:", "Location:", "Expected attendees:"), h2("Budget / 예산"), bullet("Venue:", "Catering:", "Marketing:", "Misc:"), h2("Timeline / 타임라인"), tasks("4 weeks: Venue booked", "3 weeks: Speakers confirmed", "2 weeks: Invitations sent", "1 week: Final rehearsal"), h2("Day-of Checklist / 당일 체크"), tasks("")],
  },
  {
    name: "Customer Persona",
    nameKo: "고객 페르소나",
    description: "Target customer persona profile",
    descriptionKo: "타겟 고객 페르소나 프로필",
    icon: "👤",
    category: "marketing",
    tags: ["persona", "customer", "페르소나"],
    blocks: [h2("Persona Name / 이름"), p(), h2("Demographics / 인구통계"), bullet("Age:", "Occupation:", "Location:", "Income:"), h2("Goals / 목표"), bullet(""), h2("Pain Points / 고충"), bullet(""), h2("Behavior / 행동 패턴"), bullet(""), h2("Preferred Channels / 선호 채널"), bullet(""), h2("Quote / 대표 발언"), quote("")],
  },

  // ──────────────── CUSTOM (not seeded -- user creates) ────────────────
];
